services:
  frontend:
    image: frontend
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - assessment-net

networks:
  assessment-net:
    external: true
