services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2
      - backend3
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}

  mongo:
    image: mongo:5.0                        # Puedes usar la versión que prefieras
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db                 # Volumen para persistir datos
    ports:
      - "27017:27017"                       # Mapea el puerto interno al host


  backend1:
    image: backend1
    build: ./backend
    ports:
      - "4001:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - INSTANCE_NAME=Backend 1

  backend2:
    image: backend2
    build: ./backend
    ports:
      - "4002:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - INSTANCE_NAME=Backend 2

  backend3:
    image: backend3
    build: ./backend
    ports:
      - "4003:4000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - INSTANCE_NAME=Backend 3

  inference:
    image: inference
    build: ./inference
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3
      - inference
    env_file:
      - .env

volumes:
  mongo_data: