services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2
      - backend3
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}

  backend1:
    image: backend1
    build: ./backend
    ports:
      - "4001:4000"
    env_file:
      - .env
    environment:
      - INSTANCE_NAME=Backend 1

  backend2:
    image: backend2
    build: ./backend
    ports:
      - "4002:4000"
    env_file:
      - .env
    environment:
      - INSTANCE_NAME=Backend 2

  backend3:
    image: backend3
    build: ./backend
    ports:
      - "4003:4000"
    env_file:
      - .env
    environment:
      - INSTANCE_NAME=Backend 3

  compiler:
    image: backend3
    build: ./compiler
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3
      # - compiler
    env_file:
      - .env
