services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=${BACKEND_URL}

  backend:
    build: ./backend
    ports:
      - "4000:4000"

  compiler:
    build: ./compiler
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - compiler
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - COMPILER_URL=${COMPILER_URL}

env_file: .env